# main menu navigation
menu:
  Home: /
  Services: /services
  About Us: /about
  archives: /archives
  Contact Us: /contact
#  rss: /atom.xml

# Miscelaneous
favicon: /favicon.ico

#show_post_category: true
#show_post_tags: true

active_nav: true # show active status on nav menu

sidebar: true # whether to show the sidebar
widgets:
  - links
  - recent_posts
  - tagcloud
  # - category
  # - archive
  # - tag
links:
  #- title: "GitHub"
  #  url: http://www.github.com/wayou
  #  intro: "码农之家"
  #- title: "微博"
  #  url: http://www.weibo.com/liuwayong
  #  intro: "twitter的本地化版本"
  - title: PureAccess Login
    url: https://isonaspureaccesscloud.com
    intro: "Pure Access Cloud Login"
# disqus_shortname: wayou
#duoshuo_shortname: wayouliu
#site statistic
google_analytics:
# baidu_analytics: 392796d51567e848aebf813b65cb8656
baidu_analytics:
